### ISSUE TITLE
Binder URL broken

### ISSUE THREAD

**Issue by fangohr** [oscovida/feedback#3]
In the notebooks generated (such as https://oscovida.github.io/html/South-Africa.html), there is a "Execute this Jupyter Notebook using myBinder" link at the top of the notebooks (which works) and a second one further down in the markdown before cell [5] which reads "click here to use myBinder".

The second one hasn't got the right link inserted (thus leading to a 400 error).

**Comment by RobertRosca** [comment]
Ah my bad, didn't even notice the second binder link.

Hey at least this change is a good example of why I wanted to move from the ipynb files as templates to the python files with `# %%` syntax (I should really find out what these are called, if they have a name): just did the PR from the browser as the template file is easily readable and editable without jupyter.
